export const CONSTANTS = {
    ADD_BOARD: "ADD_BOARD",
    GET_ALL_BOARDS: "GET_ALL_BOARDS",
    SET_ACTIVE_BOARD: "SET_ACTIVE_BOARD",
    ADD_CARD: "ADD_CARD",
    ADD_LIST: "ADD_LIST",
    EDIT_CARD: "EDIT_CARD",
    DELETE_CARD: "DELETE_CARD",
    EDIT_LIST_TITLE: "EDIT_LIST_TITLE",
    DELETE_LIST: "DELETE_LIST",
    DRAG_HAPPENED: "DRAG_HAPPENED",
    SEARCH_LISTS_IN_BOARD: "SEARCH_LISTS_IN_BOARD",
    GET_SEARCH_LISTS_IN_BOARD: "GET_SEARCH_LISTS_IN_BOARD",
};